Pi 21774 oAuth2.0 Filter POC
AppDirect/service-integration-sdk pull request #238
Opened 2021-01-20 10:49 UTC by ketanmulay-appdirect

PI 21774

#### Description
oAuth2.0 Filter POC

#### Manual merge checklist:
- [ ] Code Review completed
- [ ] Code coverage
- [ ] QA Validation completed
  - Testrail TestCase/Plan link:
- [ ] Approved by a PI tech lead
- [ ] Github checks all green

#### Notification(s)

2021-01-21 13:04 UTC, ketanmulay-appdirect commented
Dev Testing -

![image](https://user-images.githubusercontent.com/70201376/105354896-3bab0900-5c17-11eb-8eb9-dd911e4e6170.png)

![image](https://user-images.githubusercontent.com/70201376/105354841-27670c00-5c17-11eb-816e-50c338115e08.png)

2021-01-25 10:23 UTC, reshmakadam-appdirect approved these changes

2021-01-27 05:56 UTC, reshmakadam-appdirect submitted a review, later dismissed

2021-01-28 07:50 UTC, abidhkhan requested changes

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationService.java
> +public class DeveloperSpecificOAuth2AuthorizationService {
`DeveloperSpecificOAuth2AuthorizationService` sounds very odd.  Can we just say `OAuth2AuthorizationService`

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationService.java
> +public class DeveloperSpecificOAuth2AuthorizationService {
Should not be `interface` ?

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationSupplier.java
> +public interface DeveloperSpecificOAuth2AuthorizationSupplier {
`OAuth2AuthorizationSupplier`

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationSupplierImpl.java
> +public class DeveloperSpecificOAuth2AuthorizationSupplierImpl implements DeveloperSpecificOAuth2AuthorizationSupplier{
`OAuth2AuthorizationSupplierImpl`

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagSupplier.java
> +public interface DeveloperSpecificOAuth2FeatureFlagSupplier {
`OAuth2FeatureFlagSupplier`

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagService.java
> +public class DeveloperSpecificOAuth2FeatureFlagService {
`OAuth2FeatureFlagService`

2021-01-28 07:50 UTC, abidhkhan commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagSupplierImpl.java
> +public class DeveloperSpecificOAuth2FeatureFlagSupplierImpl implements DeveloperSpecificOAuth2FeatureFlagSupplier{
`OAuth2FeatureFlagSupplierImpl`

2021-01-28 09:35 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationService.java
> +public class DeveloperSpecificOAuth2AuthorizationService {
Fixed

2021-01-28 09:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationSupplier.java
> +public interface DeveloperSpecificOAuth2AuthorizationSupplier {
Fixed

2021-01-28 09:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationSupplierImpl.java
> +public class DeveloperSpecificOAuth2AuthorizationSupplierImpl implements DeveloperSpecificOAuth2AuthorizationSupplier{
Fixed

2021-01-28 09:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagSupplier.java
> +public interface DeveloperSpecificOAuth2FeatureFlagSupplier {
Fixed

2021-01-28 09:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagService.java
> +public class DeveloperSpecificOAuth2FeatureFlagService {
Fixed

2021-01-28 09:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2FeatureFlagSupplierImpl.java
> +public class DeveloperSpecificOAuth2FeatureFlagSupplierImpl implements DeveloperSpecificOAuth2FeatureFlagSupplier{
Fixed

2021-01-28 09:37 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificOAuth2AuthorizationService.java
> +public class DeveloperSpecificOAuth2AuthorizationService {
Fixed

2021-02-02 05:25 UTC, nsadaphal submitted a review, later dismissed
LGTM

2021-02-02 05:26 UTC, reshmakadam-appdirect submitted a review, later dismissed

2021-02-02 05:57 UTC, rajbhupendra588 submitted a review, later dismissed

2021-02-02 06:33 UTC, adityaraj-appdirect approved these changes

2021-02-02 06:52 UTC, abidhkhan submitted a review, later dismissed

2021-02-03 07:51 UTC, adityaraj-appdirect approved these changes

2021-02-03 10:18 UTC, ssanghavi-appdirect approved these changes
LGTM

2021-02-03 10:19 UTC, merged