PI-21796: Basic Auth POC in SDK
AppDirect/service-integration-sdk pull request #241
Opened 2021-01-29 04:53 UTC by rajbhupendra588

#### [PI-21796](https://appdirect.jira.com/browse/PI-21796)

#### Dependencies
[//]: # "optional, remove if none"
List additional Jira tickets or Github PRs

#### Description
Description of the PR. Make language appropriate for other engineers not involved.
-Basic Auth POC in SDK

2021-01-29 05:36 UTC, ketanmulay-appdirect requested changes

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BasicOauthSecurityConfiguration.java
> +@Order(1)
Basic auth should be of least priority. Please add @Order(101) to this class and @Order(100) on com.appdirect.sdk.web.oauth.SecurityConfiguration

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BasicOauthSecurityConfiguration.java
> +	public OAuthProviderTokenServices oauthProviderTokenServices() {
Why do we need token service for basic auth?

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BaiscOauthService.java
> +public interface BaiscOauthService {
Please change name of the interface to BasicAuthService. We dont need oAuth here.

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BaiscOauthServiceImpl.java
> +public class BaiscOauthServiceImpl implements BaiscOauthService {
Please correct class name here as well.

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BaiscOauthSupplier.java
> +public interface BaiscOauthSupplier {
Please correct name here. Do you have corresponding connector implementation for this?

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BaiscOauthSupplierImpl.java
> +public class BaiscOauthSupplierImpl implements  BaiscOauthSupplier{
Please change name.

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BasicOauthSecurityConfiguration.java
> +	public ProtectedResourceProcessingFilter oAuthSignatureCheckingFilter() {
do we need to check oAuthSignature?

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BaiscOauthSupplier.java
> +	Filter getBasicFilter();
please rename to getBasicAuthFilter

2021-01-29 05:36 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BasicOauthSecurityConfiguration.java
> +	public Filter basicSignatureCheckingFilter() {
Please rename to basicAuthenticationFilter

2021-02-01 05:03 UTC, abidhkhan approved these changes

2021-02-04 08:47 UTC, rajbhupendra588 commented
Dev Testing:- 

**Basic Auth :-** 
**With Valid username & password:-** 

![image](https://user-images.githubusercontent.com/10944722/106866920-08767880-66f3-11eb-9731-82c77e01ca6f.png)


**With InValid username & password:-** 
![image](https://user-images.githubusercontent.com/10944722/106866931-0b716900-66f3-11eb-940e-aeb4c27e5474.png)



**Auth1 :-** [Not breaking] 
![image](https://user-images.githubusercontent.com/10944722/106866945-0f04f000-66f3-11eb-8111-5bfe8654ba51.png)

2021-02-04 09:08 UTC, ketanmulay-appdirect requested changes

2021-02-04 09:08 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventService.java
> +				log.info("Password ->{}",pass);
Please remove password from logs

2021-02-04 11:48 UTC, reshmakadam-appdirect submitted a review, later dismissed

2021-02-08 04:44 UTC, nsadaphal submitted a review, later dismissed
LGTM

2021-02-10 06:23 UTC, ketanmulay-appdirect requested changes

2021-02-10 06:23 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/appmarket/DeveloperSpecificAppmarketBasicAuthCredentialsSupplier.java
> +public interface DeveloperSpecificAppmarketBasicAuthCredentialsSupplier {
Can you please rename it to BasicAuthCredentialsSupplier? For new classes inserted we are not following old naming convention.

2021-02-10 06:23 UTC, ketanmulay-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/DeveloperSpecificAppmarketBasicAuthCredentialsConsumerDetailsService.java
> +class DeveloperSpecificAppmarketBasicAuthCredentialsConsumerDetailsService implements ConsumerDetailsService {
Please rename to BasicAuthCredentialsConsumerDetailsService

2021-02-10 06:49 UTC, rajbhupendra588 commented
Dev Testing :- 



**Basic Auth with Valid credential :-** 

![image](https://user-images.githubusercontent.com/10944722/107473579-ef5c4480-6b96-11eb-9433-cb1a0edd9783.png)





**Basic Auth with InValid credential:-** 
 
![image](https://user-images.githubusercontent.com/10944722/107473573-ec615400-6b96-11eb-9cf4-83f3f9f2dd44.png)





**OAuth1 with Valid credential :-**  

![image](https://user-images.githubusercontent.com/10944722/107473587-f1260800-6b96-11eb-8cf4-b35bc4775f4d.png)

2021-02-10 06:53 UTC, raushan-appdirect approved these changes
LGTM

2021-02-10 07:03 UTC, nsadaphal approved these changes

2021-02-10 11:34 UTC, ketanmulay-appdirect approved these changes
LGTM

2021-02-10 11:39 UTC, merged