PI-22232  Configure BasicAuth Filter supplier in SDK and update BasicAuthSecurityConfiguration
AppDirect/service-integration-sdk pull request #255
Opened 2021-03-09 12:01 UTC by nsadaphal

#### [PI-22232](https://appdirect.jira.com/browse/PI-22232)

#### Description
1. Using OAuth2 API's for Basic Auth
  Event API's
  Domain Association API's
  Migration API's
  Restriction API's
2. Updating BasicAuthSecurityConfiguration to correct use of user details for authorization.
3. Integrating  BasicAuthSecurityConfiguration to ConnectorSdkConfiguration.
4. Adding authentication provider in BasicAuthSecurityConfiguration

#### Manual merge checklist:
- [ ] Code Review completed
- [ ] Code coverage
- [ ] QA Validation completed
  - Testrail TestCase/Plan link:
- [ ] Approved by a PI tech lead
- [ ] Github checks all green

#### Notification(s)

#### Dev Testing
**Basic Auth for Event API:-**

**1. With Valid Credential:-**
<img width="1239" alt="Screenshot 2021-03-10 at 6 48 26 PM" src="https://user-images.githubusercontent.com/62536596/110734422-d1453b00-824d-11eb-959c-a9aed76c8f1b.png">

<img width="832" alt="Screenshot 2021-03-10 at 6 48 39 PM" src="https://user-images.githubusercontent.com/62536596/110734432-d4d8c200-824d-11eb-9e60-a3bb9c90b308.png">

**2. With InValid Credential:-**

<img width="1254" alt="Screenshot 2021-03-10 at 7 24 02 PM" src="https://user-images.githubusercontent.com/62536596/110734500-f639ae00-824d-11eb-9956-b8190f6675dc.png">

![Screenshot 2021-03-10 at 7 23 53 PM](https://user-images.githubusercontent.com/62536596/110734508-fa65cb80-824d-11eb-903b-c438d01c2105.png)

**OAuth2 for Event API:-**

**1. With Valid Credential:-**

<img width="1237" alt="Screenshot 2021-03-10 at 6 52 09 PM" src="https://user-images.githubusercontent.com/62536596/110734568-17020380-824e-11eb-9572-5f166ec9b349.png">

<img width="1620" alt="Screenshot 2021-03-10 at 6 52 24 PM" src="https://user-images.githubusercontent.com/62536596/110734575-1b2e2100-824e-11eb-9d8f-ed7ae3c23e67.png">

**2. With InValid Credential:-**

<img width="1241" alt="Screenshot 2021-03-10 at 7 28 06 PM" src="https://user-images.githubusercontent.com/62536596/110734612-30a34b00-824e-11eb-919a-33a4cd746534.png">

**Tested for Internal API**
**1. With OAuth2:**

<img width="1242" alt="Screenshot 2021-03-10 at 6 50 45 PM" src="https://user-images.githubusercontent.com/62536596/110734669-4fa1dd00-824e-11eb-8b63-6834f0fd266c.png">

<img width="1648" alt="Screenshot 2021-03-10 at 6 50 56 PM" src="https://user-images.githubusercontent.com/62536596/110734795-8d066a80-824e-11eb-8473-ce753064c45b.png">

**2. With Basic Auth:**
<img width="1269" alt="Screenshot 2021-03-10 at 7 29 33 PM" src="https://user-images.githubusercontent.com/62536596/110734742-74965000-824e-11eb-9a7e-4fd098ff7186.png">

![Screenshot 2021-03-10 at 7 29 47 PM](https://user-images.githubusercontent.com/62536596/110734752-7b24c780-824e-11eb-8c6d-a7b99d72bb43.png)

2021-03-09 13:50 UTC, ketanmulay-appdirect submitted a review, later dismissed
LGTM

2021-03-09 14:04 UTC, raushan-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/BasicAuthSecurityConfiguration.java
> +                .antMatchers("/api/v2/basic/integration/**", "/api/v2/basic/domainassociation/**", "/api/v2/basic/migration/**", "/api/v2/basic/restrictions/**")
We don't need separate endpoints and configuration to support basic auth, we can just add a basic auth filter to the main configuration and existing APIs will support basic as well with OAuth1 and OAuth2

Let's have a discussion offline

2021-03-10 03:13 UTC, nsadaphal commented on src/main/java/com/appdirect/sdk/web/oauth/BasicAuthSecurityConfiguration.java
> +                .antMatchers("/api/v2/basic/integration/**", "/api/v2/basic/domainassociation/**", "/api/v2/basic/migration/**", "/api/v2/basic/restrictions/**")
Sure, Just adding a basic auth filter in the main configuration will not make it work, We require other beans and configurations for basic auth to work.
Also by keeping configure separate we can have clean and readable code.

2021-03-11 04:09 UTC, nsadaphal commented on src/main/java/com/appdirect/sdk/web/oauth/BasicAuthSecurityConfiguration.java
> +                .antMatchers("/api/v2/basic/integration/**", "/api/v2/basic/domainassociation/**", "/api/v2/basic/migration/**", "/api/v2/basic/restrictions/**")
@raushan-appdirect As discussed updated the implementation for basic auth to use the same Oauth2 endpoints.
Thanks

2021-03-11 04:37 UTC, raushan-appdirect requested changes
Could you please add some UTs

2021-03-11 04:37 UTC, raushan-appdirect commented on src/main/java/com/appdirect/sdk/web/oauth/model/SessionRequestMatcher.java
> +    private static final String RESTRICTIONS_PATH = "/api/v1/restrictions/**";
I guess here the three APIs should be v2

2021-03-11 04:43 UTC, nsadaphal commented on src/main/java/com/appdirect/sdk/web/oauth/model/SessionRequestMatcher.java
> +    private static final String RESTRICTIONS_PATH = "/api/v1/restrictions/**";
updated

2021-03-11 06:28 UTC, raushan-appdirect approved these changes
💯

2021-03-11 07:16 UTC, ketanmulay-appdirect approved these changes
LGTM

2021-03-11 07:17 UTC, merged